controllers/ReportController.php
<?php

namespace app\controllers;

use yii;

class ReportController extends \yii\web\Controller {

    public function actionIndex() {
        return $this->render('index');
    }
/*
  public function actionReport1() {
        
        $sql = "SELECT 
            h.hoscode,h.hosname
            ,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
                     AND p.typearea in (1,3)
             ) as 'total'
            ,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
               AND p.typearea in (1,3) AND p.RELIGION = 1
              ) as 'buddha'
            ,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
               AND p.typearea in (1,3) AND p.RELIGION != 1
              ) as 'other'
             from chospital_amp h
WHERE h.hoscode in ('08010','08011','08012','08013')             
";
        //$rawData = \yii::$app->db->createCommand($sql)->queryAll();
        //print_r($rawData);
        
        try {
            $rawData = \Yii::$app->db->createCommand($sql)->queryAll();
        } catch (\yii\db\Exception $e) {
            throw new \yii\web\ConflictHttpException('sql error');
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rawData,
            'pagination' => FALSE,
        ]);
        return $this->render('report1', [
                    'dataProvider' => $dataProvider,
                    'rawData'=>$rawData
        ]);
    }
    
*/    
    
    public function actionReport1() {
        $sql = "SELECT 
h.hoscode,h.hosname
,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
	 AND p.typearea in (1,3)
 ) as 'total'
,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
   AND p.typearea in (1,3) AND p.RELIGION = 1
  ) as 'buddha'
,(select COUNT(DISTINCT p.HOSPCODE,p.PID) from person p where p.HOSPCODE = h.hoscode
   AND p.typearea in (1,3) AND p.RELIGION != 1
  ) as 'other'
 from chospital_amp h
WHERE h.hoscode in ('08010','08011','08012','08013')";
        try {
            $rawData = \Yii::$app->db->createCommand($sql)->queryAll();
        } catch (\yii\db\Exception $e) {
            throw new \yii\web\ConflictHttpException('sql error');
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rawData,
            'pagination' => FALSE,
        ]);
        return $this->render('report1', [
                    'dataProvider' => $dataProvider,
                    'rawData'=>$rawData
        ]);
    }
    public function actionReport3($hoscode) {
        $sql = "select hospcode,name,lname,RELIGION from person where hospcode=$hoscode";
        try {
            $rawData = \Yii::$app->db->createCommand($sql)->queryAll();
        } catch (\yii\db\Exception $e) {
            throw new \yii\web\ConflictHttpException('sql error');
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rawData,
            'pagination' => FALSE,
        ]);
        return $this->render('report3', [
                    'dataProvider' => $dataProvider,
                    'sql' => $sql
        ]);
    }

    public function actionReport4($hoscode) {
        $sql = "select hospcode,name,lname,RELIGION from person where  RELIGION != 1 and typearea in (1,3) and hospcode=$hoscode";
        try {
            $rawData = \Yii::$app->db->createCommand($sql)->queryAll();
        } catch (\yii\db\Exception $e) {
            throw new \yii\web\ConflictHttpException('sql error');
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rawData,
            'pagination' => FALSE,
        ]);
        return $this->render('report4', [
                    'dataProvider' => $dataProvider,
                    'sql' => $sql
        ]);
    }

}

views/report/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>report/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/report/report1.php
<?php

use kartik\grid\GridView;
use yii\helpers\Html;
use miloschuman\highcharts\Highcharts;

$this->params['breadcrumbs'][] = ['label' => 'รายงาน', 'url' => ['report/report1']];
$this->params['breadcrumbs'][] = 'รายบุคคล';
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'panel' => [
        'before' => 'รายชื่อผู้ถูกวินิจฉัยป่วยด้วยโรคเบาหวานและความดันโลหิตสูง',
        'after' => 'ประมวลผล ณ ' . date('Y-m-d H:i:s')
    ],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute' => 'hoscode',
            'header' => 'รหัสสถานบริการ',
        ],
        [
            'attribute' => 'hosname',
            'format' => 'raw',
            'value' => function($model) {
                $hoscode = $model['hoscode'];
                $hosname = $model['hosname'];
                return Html::a(Html::encode($hosname), ['report/report4', 'hoscode' => $hoscode]);
            }
        ],
        [
            'attribute' => 'total',
            'header' => 'ประชากรทั้งหมด(คน)'
        ],
        [
            'attribute' => 'buddha',
            'header' => 'ศาสนาพุทธ (คน)'
        ],
        [
            'attribute' => 'other',
            'header' => 'อื่นๆ (คน)'
        ],
    ]
]);
?>
<div class="alert alert-danger">
    <?= $sql ?>

</div>
<div id="chart">

    <?php
    echo Highcharts::widget([
        'scripts' => [
            'highcharts-more',
            'themas/grit'
        ]
    ]);
    ?>
</div>

<?php
$categ = [];
for ($i = 0; $i < count($rawData); $i++) {
    $categ[] = $rawData[$i]['hosname'];
}
$js_categories = implode("','", $categ);
$data = [];
for ($i = 0; $i < count($rawData); $i++) {
    $data [] = $rawData[$i]['buddha'];
}
$js_data = implode(",", $data);


//เริ่ม สร้าง กราฟ
$this->registerJs("
        
Highcharts.chart('chart', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Monthly Average Rainfall'
    },
    subtitle: {
        text: 'Source: WorldClimate.com'
    },
    xAxis: {
        categories: [
            '$js_categories'
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'นับถือศาสนาพุทธ(คน)'
        }
    },
    tooltip: {
        headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',
        pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td>' +
            '<td style=\"padding:0\"><b>{point.y:.1f} คน</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name: 'ศาสนาพุทธ จำนวน : ',
        data: [$js_data]

    }, ]
});



")
    
// จบกราฟ
?>

views/report/report3.php
<?php
use kartik\grid\GridView;
use yii\helpers\Html;
$this->params['breadcrumbs'][] = ['label' => 'รายงาน', 'url' => ['report/report1']];
$this->params['breadcrumbs'][] = 'รายบุคคล';
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'panel' => [
        'before' => 'dd',
        'after' => 'ประมวลผล ณ ' . date('Y-m-d H:i:s')
    ],
]);
?>
<div class="alert alert-danger">
    <?=$sql?>
    
</div>

views/report/report4.php
<?php
use kartik\grid\GridView;
use yii\helpers\Html;
$this->params['breadcrumbs'][] = ['label' => 'รายงาน', 'url' => ['report/report1']];
$this->params['breadcrumbs'][] = 'รายบุคคล';
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'panel' => [
        'before' => 'dd',
        'after' => 'ประมวลผล ณ ' . date('Y-m-d H:i:s')
    ],
]);
?>
<div class="alert alert-danger">
    <?=$sql?>
    
</div>